services:
  nginx:
    image: nginx:stable-alpine
    container_name: ethqna-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/ethqna.xyz/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ethqna.xyz/privkey.pem:/etc/nginx/certs/privkey.pem:ro  # Your certs folder with cert.pem and key.pem
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ethqna-frontend
    expose:
      - "5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ethqna-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
